/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grp_project;
import java.io.IOException;
import edu.cmu.sphinx.api.Configuration;
import edu.cmu.sphinx.api.LiveSpeechRecognizer;
import edu.cmu.sphinx.api.SpeechResult;
/**
 *
 * @author Mihir
 */
public class App_UI extends javax.swing.JFrame {

    /**
     * Creates new form App_UI
     */
    public App_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        mic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setForeground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        jLabel1.setText("VOICE ASSISTANT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        mic.setBackground(new java.awt.Color(0, 153, 153));
        mic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp_project/icon/microphone.png"))); // NOI18N
        mic.setText("click to speak");
        mic.setToolTipText("click and command");
        mic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mic.setContentAreaFilled(false);
        mic.setFocusPainted(false);
        mic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mic.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mic.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mic.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                micMouseMoved(evt);
            }
        });
        mic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                micMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                micMouseExited(evt);
            }
        });
        mic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(mic, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(mic)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 468, 196));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void micActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micActionPerformed
         Configuration config = new Configuration();
	
		config.setAcousticModelPath("resource:/edu/cmu/sphinx/models/en-us/en-us");
		config.setDictionaryPath("src\\resources\\1295.dic");
		config.setLanguageModelPath("src\\resources\\1295.lm");
        
		try {
			LiveSpeechRecognizer speech = new LiveSpeechRecognizer(config);
			speech.startRecognition(true);
			
			SpeechResult speechResult = null;
			outer:
			while((speechResult=speech.getResult()) != null) {
				String VoiceCommand = speechResult.getHypothesis();
			 	System.out.println("Voice Command is: " + VoiceCommand);
				
				if(VoiceCommand.equalsIgnoreCase("Open Edge")) {
					Runtime.getRuntime().exec("cmd.exe /c start msedge www.google.com");
                                        //text.setText("Voice command is: "+VoiceCommand+"\n");
				}else if(VoiceCommand.equalsIgnoreCase("Close Edge")) {
					Runtime.getRuntime().exec("cmd.exe /c TASKKILL /IM msedge.exe");
                                        //text.setText("Voice command is: "+VoiceCommand+"\n");
				}
                                else if(VoiceCommand.equalsIgnoreCase("Open calculator")) {
					Runtime.getRuntime().exec("cmd.exe /c calc");
                                        //text.setText("Voice command is: "+VoiceCommand+"\n");
				}else if(VoiceCommand.equalsIgnoreCase("Close calculator")) {
					Runtime.getRuntime().exec("cmd.exe /c TASKKILL /F /IM calculator.exe");
                                        //text.setText("Voice command is: "+VoiceCommand+"\n");
				}
                                else if(VoiceCommand.equalsIgnoreCase("Open gmail")) {
					Runtime.getRuntime().exec("cmd.exe /c start msedge www.gmail.com");
                                        //text.setText("Voice command is: "+VoiceCommand+"\n");
				}else if(VoiceCommand.equalsIgnoreCase("Close gmail")) {
					Runtime.getRuntime().exec("cmd.exe /c TASKKILL /IM msedge.exe");
                                        //text.setText("Voice command is: "+VoiceCommand+"\n");
				}
                                else if(VoiceCommand.equalsIgnoreCase("Open store")) {
					Runtime.getRuntime().exec("cmd.exe /c start ms-windows-store:");
                                        //text.setText("Voice command is: "+VoiceCommand+"\n");
				}else if(VoiceCommand.equalsIgnoreCase("Close store")) {
					Runtime.getRuntime().exec("cmd.exe /c taskkill /f /im WinStore.App.exe");
                                        //text.setText("Voice command is: "+VoiceCommand+"\n");
				}
                                else if(VoiceCommand.equalsIgnoreCase("stop sensing")){
                                     //text.setText("Voice command is: "+VoiceCommand+"\n");
                                     dispose();
                                     break outer;}
       
			}
                        	
		}catch (IOException e) {
			e.printStackTrace();
		}    
    }//GEN-LAST:event_micActionPerformed

    private void micMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micMouseMoved

    }//GEN-LAST:event_micMouseMoved

    private void micMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micMouseClicked
        
    }//GEN-LAST:event_micMouseClicked

    private void micMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micMouseExited

    }//GEN-LAST:event_micMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mic;
    // End of variables declaration//GEN-END:variables
}
